// Copies the KaTeX web fonts into public/katex/fonts so equation rendering is
// fully offline (no CDN). Also emits src/core/layout/katex-css.generated.ts
// (a plain TS string) so Vite, Vitest AND Playwright's loader all get the CSS
// without depending on bundler `?raw`/`?inline` query handling.
import { cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const fontsSrc = path.join(root, "node_modules", "katex", "dist", "fonts");
const fontsDest = path.join(root, "public", "katex", "fonts");
const cssSrc = path.join(root, "node_modules", "katex", "dist", "katex.min.css");
const generatedTs = path.join(root, "src", "core", "layout", "katex-css.generated.ts");

mkdirSync(fontsDest, { recursive: true });
cpSync(fontsSrc, fontsDest, { recursive: true });
console.log(`copied ${path.relative(root, fontsSrc)} → ${path.relative(root, fontsDest)}`);

const css = readFileSync(cssSrc, "utf8");
writeFileSync(
  generatedTs,
  `/** Generated by scripts/copy-katex.mjs — do not edit. KaTeX stylesheet inlined\n * so equations render fully offline in the app, the node PDF exporter and tests. */\nexport const KATEX_CSS: string = ${JSON.stringify(css)};\n`,
  "utf8",
);
console.log(`generated ${path.relative(root, generatedTs)} (${css.length} chars)`);